---
- name: Setup k3s agents
  shell: >
    curl -sfL https://get.k3s.io | sh -s - agent 
    --token {{ k3s_token }}
    --server "https://{{ hostvars[master_node].host_address }}:6443"
  # script: 
  #   cmd: "~/k3s-install.sh agent --token {{ k3s_token }} --server 'https://{{ hostvars[master_node].host_address }}:6443'" 
  become: true
