---
- name: Ensure ~/.kube directory exists.
  file:
    path: ~/.kube
    state: directory
  delegate_to: localhost
  become: false
  run_once: true

- name: Copy K8s config file from master to local.
  fetch:
    src: "{{ kube_config }}"
    dest: "~/.kube/config-pi-cluster"
    flat: true
  delegate_to: "{{ master_node }}"
  run_once: true
  become: true

- name: Ensure ~/.kube directory exists.
  file:
    path: ~/.kube
    state: directory

- name: Copy K8s config file from master to nodes.
  copy:
    src: "~/.kube/config-pi-cluster"
    dest: "/home/{{ ansible_ssh_user }}/.kube/config"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0644'
  become: true
