---
- name: Setup k3s servers 
  shell: >
    sh "/home/{{ ansible_ssh_user }}/k3s_install.sh" server 
    --token {{ k3s_token }} 
    --datastore-endpoint "postgres://{{ postgres_user }}:{{ postgres_password }}@{{ postgres_host }}:5432/k3s?sslmode={{ ssl_mode }}"
    --tls-san {{ hostvars[master_node].host_address }}
  become: true
