---
- name: Setup k3s servers 
  shell: >
    sh "/home/{{ ansible_ssh_user }}/k3s_install.sh" server 
    --token {{ k3s_token }} 
    --tls-san {{ hostvars[master_node].host_address }}
  become: true
#for multiple servers add: --datastore-endpoint "postgres://{{ postgres_user }}:{{ postgres_password }}@{{ postgres_host }}:5432/k3s?sslmode={{ ssl_mode }}"
- name: Fix server IP in "k3s.yaml"
  lineinfile:
    path: "{{ kube_config }}"
    regexp: '127\.0\.0\.1'
    line: "    server: https://{{ hostvars[inventory_hostname].host_address }}:6443"
    state: present
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0644'
  become: true
