---
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=clusteruser
      - POSTGRES_PASSWORD
    volumes:
      - /home/pi/.postgres/data/:/var/lib/postgresql/data/
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9080:8080
