---
- name: Create .ssh directory
  file:
    path: "{{ ssh_folder }}"
    state: directory
- name: Create empty authorized_keys file
  file:
    path: "{{ ssh_folder }}/authorized_keys"
    state: touch
- name: put pubkey
  lineinfile:
    path: "{{ ssh_folder }}/authorized_keys"
    line: "{{ pubkey }}"
    state: present

# - name: Update apt cache
#   apt:
#     update_cache: true
#   become: true
# - name: Install sshpass
#   apt:
#     name: sshpass
#     state: latest
#   delegate_to: localhost
#   become: true
- name: Install python3-pip
  apt:
    update_cache: true
    name: python3-pip
    state: latest
  become: true
- name: Install openshift pip plugin
  pip:
    name: openshift
  become: true
