---
- name: Check namespaces fro k8s.
  include_tasks: check-k8s.yml
  when: use_k8s

- name: Deploy manifests defined in manifests.
  include_tasks: deploy-manifest.yml
  loop: "{{ k8s_manifests }}"
  loop_control:
    loop_var: outer_item
