---
- name: Setup k3s Cluster
  hosts: cluster

  pre_tasks:
    - import_tasks: tasks/update-hosts.yml
      tags: ["always"]

    - import_tasks: tasks/cgroup-features.yml
      tags: ["always"]

    - import_tasks: tasks/setup-network.yml
      when:
        - ansible_distribution_version == "10"
        - deploy_target != 'docker'
      tags: ["always"]

    - import_role:
        name: deanh.docker-setup
      # when: use_docker
      tags: ["always", "docker"]

    - import_role:
        name: deanh.containerd-setup
      # when: not use_docker
      tags: ["always", "containerd"]

    - name: Set the master node IP.
      set_fact:
        kubernetes_master_ip: "{{ hostvars[k3s_master_node].host_address }}"
      when: "'agents' in group_names"
      tags: ["always"]

  tasks:
    - include_tasks: tasks/setup-external-database.yml
      when: "'databases' in group_names"
      tags: ['k3s', 'database']

    - include_role: 
        name: deanh.k3s-docker-registry
      vars: 
        docker_registry_domain: registry.picluster.com
      when: "'servers' in group_names"
      tags: ['k3s', 'docker-registry']
