---
- name: Gather package facts
  package_facts:
    manager: auto

- name: Install "git"
  package:
    # update_cache: true
    name: git
    state: latest
  register: git_installed
  run_once: true
  become: true

- name: Install sshpass
  package:
    # update_cache: true
    name: sshpass
    state: latest
  when: '"sshpass" not in ansible_facts.packages'
  run_once: true
  become: true

- name: Install "python3-pip"
  package:
    name: python3-pip
    state: latest
  when: '"python3-pip" not in ansible_facts.packages'
  register: python3_pip_installed
  run_once: true
  become: true

- name: Install "pexpect" pip plugin
  pip:
    name: pexpect
  when: (python3_pip_installed is changed) or (python3_pip_installed is succeeded)
  run_once: true
  become: true

- name: Install "openshift" pip plugin
  pip:
    name: openshift
  when: (python3_pip_installed is changed) or (python3_pip_installed is succeeded)
  run_once: true
  become: true

- name: Install "fabric" pip plugin
  pip:
    name: fabric
  when:
    - (python3_pip_installed is changed) or (python3_pip_installed is succeeded)
  run_once: true
  become: true

# - name: Update apt cache and do full-upgrade
#   package:
#     update_cache: true
#     # upgrade: full
#   run_once: true
#   become: true
