---
- name: Ensure ~/.kube directory exists.
  file:
    path: ~/.kube
    state: directory
  delegate_to: localhost
  become: false
  run_once: true

- name: Copy K8s config file from master to local.
  fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "~/.kube/config-dramble-{{ deploy_target }}"
    flat: true
  delegate_to: "{{ k3s_master_node }}"
  run_once: true
  become: true

- name: Ensure ~/.kube directory exists.
  file:
    path: ~/.kube
    state: directory
  when: "'agents' in group_names"

- name: Copy K8s config file from master to nodes.
  copy:
    src: "~/.kube/config-dramble-{{ deploy_target }}"
    dest: "~/.kube/config"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0644'
  # delegate_to: "{{ k3s_master_node }}"
  when: "'agents' in group_names"
  # run_once: true
