---
- name: Create "{{ postgres_folder }}" directory
  file:
    path: "{{ postgres_folder }}"
    state: directory

# - name: Create "{{ postgres_folder }}/{{ env_file_path }}" file
#   file:
#     path: "{{ postgres_folder }}/{{ env_file_path }}"
#     state: touch

# - name: Add environment variables to "{{ postgres_folder }}/{{ env_file_path }}"
#   lineinfile:
#     path: "{{ postgres_folder }}/{{ env_file_path }}"
#     line: "POSTGRES_PASSWORD={{ postgres_password }}"
#     state: present

- name: Create "{{ postgres_folder }}/{{ env_file_path }}" file
  copy:
    src: "{{ postgres_folder }}/{{ env_file_path }}"
    dest: "{{ postgres_folder }}/docker-compose.yml"

- name: Compose postgres
  shell: >
    docker compose --project-name postgres
    -f "{{ postgres_folder }}/docker-compose.yml"
    up -d
  become: true
