---
- hosts: localhost
  tasks:
  - name: Create .ssh directory
    file:
      path: "/home/deanh/foo"
      state: directory
  - name: create empty file
    file:
      path: "/home/deanh/foo/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: "/home/deanh/foo/authorized_keys"
      line: "{{ pubkey }}"
