---
# Docker
# Used only for Debian/Ubuntu. Switch 'stable' to 'nightly' if needed.
docker_apt_release_channel: stable
docker_apt_arch: '{{ (ansible_architecture == "aarch64") | ternary("arm64", "armhf") }}'
docker_apt_dist: "{{ (ansible_architecture == 'aarch64') | ternary(ansible_distribution, 'Raspbian') | lower }}"
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ docker_apt_dist }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true
docker_apt_gpg_key: https://download.docker.com/linux/{{ docker_apt_dist }}/gpg

# for manual installs
docker_compose_version: v2.9.0
docker_script_arch: '{{ (ansible_architecture == "aarch64") | ternary("aarch64", "armv6") }}'
