---
- name: Go go go!
  hosts: all
  vars_files: 
    - secret.yml

  vars:
    # ansible_python_interpreter: python
    k8s_kubeconfig: /etc/rancher/k3s/k3s.yaml
    k8s_manage_namespace: false
    k8s_no_log: false
    k8s_manifests_base_dir: manifests/
    k8s_manifests:
      - dir: docker-registry
        namespace: registry

  pre_tasks:
    - import_tasks: tasks/cgroup-features.yml
      tags: ["always"]

    - import_tasks: tasks/prepare-system.yml
      tags: ["always"]

    - import_tasks: tasks/setup-network.yml
      when:
        - ansible_distribution_version == "10"
        - deploy_target != 'docker'

    - import_tasks: tasks/setup-docker.yml
      tags: ["always"]

    - import_tasks: tasks/setup-containerd.yml
      tags: ["always"]

    - name: Set the master node IP.
      set_fact:
        kubernetes_master_ip: "{{ hostvars[k3s_master_node].ansible_host }}"
      tags: ["always"]
      when: "'agents' in group_names"

  tasks:
    - include_tasks: tasks/setup-external-database.yml
      tags: ["database"]
      when: "'databases' in group_names"

    - include_tasks: tasks/setup-docker-registry.yml
      tags: ["registry"]
      when: "'registries' in group_names"

    - include_tasks: tasks/setup-k3s.yml
      tags: ["k3s"]

    - import_tasks: tasks/k8s-config.yml
      tags: ['k3s']

    - import_role:
        name: geerlingguy.k8s_manifests
      tags: ['k3s', 'registry']
      when: "'servers' in group_names"
#      delegate_to: "{{ groups.servers[0] }}"
#      run_once: true

  handlers:
    - name: Restart containerd
      service:
        name: containerd
        state: restarted
      listen: "restart containerd"
#      when: "'registries' in group_names"
