---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-registry-ingress
  namespace: {{ manifest_namespace }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: {{ docker_registry_domain }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: docker-registry
                port:
                  number: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: {{ manifest_namespace }}
  labels:
    run: docker-registry
spec:
  selector:
    app: docker-registry
  ports:
    - protocol: http
      port: 5000
      targetPort: 5000

# TLS Secret for Docker registry Ingress.
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ manifest_namespace }}-tls-cert
  namespace: {{ manifest_namespace }}
data:
  tls.key: {{ docker_registry_key | b64encode }}
  tls.crt: {{ docker_registry_crt | b64encode }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: {{ manifest_namespace }}
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry
          env:
            - name: REGISTRY_HTTP_SECRET
              value: {{ docker_registry_http_secret }}
            - name: REGISTRY_HTTP_ADDR
              value: ":5000"
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
          ports:
          - name: http
            containerPort: 5000
          volumeMounts:
          - name: docker-registry-data
            mountPath: /var/lib/registry
      volumes:
        - name: docker-registry-data
          persistentVolumeClaim:
            claimName: registry-pvc
